// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKXup2arcUutoCMpICjTmOfZZlYA9v2nw',
    appId: '1:162651526848:web:f6cab56217f4b30bf6bf25',
    messagingSenderId: '162651526848',
    projectId: 'flutter-firebase-1719d',
    authDomain: 'flutter-firebase-1719d.firebaseapp.com',
    storageBucket: 'flutter-firebase-1719d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDICQt3IPQc7QDxmo_VDsS5pS-EWDvusnM',
    appId: '1:162651526848:android:00aae294f3f42b7af6bf25',
    messagingSenderId: '162651526848',
    projectId: 'flutter-firebase-1719d',
    storageBucket: 'flutter-firebase-1719d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkEjoTXf4soZBOLPmVsQJH6BdZRExemHQ',
    appId: '1:162651526848:ios:8cb1f884a92c8499f6bf25',
    messagingSenderId: '162651526848',
    projectId: 'flutter-firebase-1719d',
    storageBucket: 'flutter-firebase-1719d.firebasestorage.app',
    iosBundleId: 'com.example.flappyBird',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkEjoTXf4soZBOLPmVsQJH6BdZRExemHQ',
    appId: '1:162651526848:ios:d1c80f89227e95c6f6bf25',
    messagingSenderId: '162651526848',
    projectId: 'flutter-firebase-1719d',
    storageBucket: 'flutter-firebase-1719d.firebasestorage.app',
    iosBundleId: 'com.example.flappyBirdMain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKXup2arcUutoCMpICjTmOfZZlYA9v2nw',
    appId: '1:162651526848:web:711dab11bcb1fb39f6bf25',
    messagingSenderId: '162651526848',
    projectId: 'flutter-firebase-1719d',
    authDomain: 'flutter-firebase-1719d.firebaseapp.com',
    storageBucket: 'flutter-firebase-1719d.firebasestorage.app',
  );
}
